name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

env:
  PACKAGE_NAME: "lccs"
  MODULE_NAME: "lccs"
  OWNER: "brazil-data-cube"

jobs:
  # Extract tag details
  details:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.release.outputs.new_version }}
      suffix: ${{ steps.release.outputs.suffix }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      clean_version: ${{ steps.clean_version.outputs.clean_version }}
      is_prerelease: ${{ steps.prerelease.outputs.is_prerelease }}

    steps:
      - uses: actions/checkout@v4

      - name: Extract tag and Details
        id: release
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            NEW_VERSION=$(echo $TAG_NAME | awk -F'-' '{print $1}')
            SUFFIX=$(echo "$NEW_VERSION" | grep -oP '(a|b|rc)[0-9]+' | tr -d '\n' || true)
            echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
            echo "suffix=${SUFFIX:-}" >> "$GITHUB_OUTPUT"
            echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
          else
            echo "No tag found"
            exit 1
          fi

      - name: Extract clean version (remove 'v')
        id: clean_version
        run: |
          RAW="${{ steps.release.outputs.new_version }}"
          CLEAN="${RAW#v}"
          echo "clean_version=$CLEAN" >> $GITHUB_OUTPUT

      - name: Detect prerelease
        id: prerelease
        run: |
          TAG="${{ steps.release.outputs.tag_name }}"
          if [[ "$TAG" =~ (a[0-9]+|b[0-9]+|rc[0-9]+)$ ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

  # Detect branch and updated version
  detect-branch:
    needs: details
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.detect.outputs.branch }}
      version: ${{ steps.version.outputs.clean }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect branch for tag
        id: detect
        run: |
          BRANCH=$(git branch -r --contains "$GITHUB_SHA" | head -n 1 | sed 's/origin\///' | tr -d ' ')
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Extract version (remove leading v)
        id: version
        run: |
          CLEAN="${GITHUB_REF#refs/tags/v}"
          echo "clean=$CLEAN" >> $GITHUB_OUTPUT

  bump-version:
    needs: detect-branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BRANCH: ${{ needs.detect-branch.outputs.branch }}
      VERSION: ${{ needs.detect-branch.outputs.version }}

    steps:
      - name: Checkout correct branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ env.BRANCH }}

      - name: Update pyproject.toml version
        run: |
          sed -i "s/^version = .*/version = \"${VERSION}\"/" pyproject.toml

      - name: Validate pyproject.toml
        run: |
          pip install validate-pyproject
          validate-pyproject pyproject.toml

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pyproject.toml

          if git diff --cached --quiet; then
            echo "No version changes detected. Skipping commit."
          else
            git commit -m "Release ${VERSION}: update version"
            git push origin HEAD:${BRANCH}
          fi

      - name: Upload updated pyproject
        uses: actions/upload-artifact@v4
        with:
          name: updated-project
          path: |
            pyproject.toml

  # Check version on Pypi
  check_pypi:
    needs: details
    runs-on: ubuntu-latest

    steps:
      - name: Fetch information from PyPI
        run: |
          response=$(curl -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json || echo "{}")
          latest_previous_version=$(echo $response | grep -oP '"releases":\{"\K[^"]+' | sort -rV | head -n 1)
          if [ -z "$latest_previous_version" ]; then
            echo "Package not found on PyPI."
            latest_previous_version="0.0.0"
          fi
          echo "latest_previous_version=$latest_previous_version" >> $GITHUB_ENV

      - name: Compare versions and exit if not newer
        run: |
          NEW_VERSION=${{ needs.details.outputs.new_version }}
          LATEST_VERSION=$latest_previous_version
          if [ "$(printf '%s\n' "$LATEST_VERSION" "$NEW_VERSION" | sort -rV | head -n 1)" != "$NEW_VERSION" ] \
            || [ "$NEW_VERSION" == "$LATEST_VERSION" ]; then
            echo "The new version $NEW_VERSION is not greater than $LATEST_VERSION"
            exit 1
          fi

  # Build Package
  setup_and_build:
    needs: [details, check_pypi, bump-version]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: updated-project
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build and twine
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build twine

      - name: Generate stubs
        run: |
          python3 -m pip install mypy
          stubgen ${{ env.MODULE_NAME }} -o .

      - name: Build source and wheel distribution
        run: |
          python3 -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  # Publish in TestPyPI
  testpypi_publish:
    name: Upload to TestPyPI (SAFE TEST)
    needs: [setup_and_build, details]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload to TestPyPI using twine
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python3 -m pip install twine
          python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*

  # Publish to PYPI
  pypi_publish:
    name: Upload release to PyPI
    needs: [testpypi_publish, setup_and_build, details]
    if: ${{ needs.details.outputs.is_prerelease == 'false' }}
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  # Pre-Release and Release jobs
  github_prerelease:
    name: Create GitHub Pre-Release
    runs-on: ubuntu-latest
    needs:
      - details
      - setup_and_build
      - testpypi_publish

    if: >
      needs.testpypi_publish.result == 'success' &&
      needs.details.outputs.is_prerelease == 'true'

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.details.outputs.tag_name }}
          name: "Version ${{ needs.details.outputs.clean_version }}"
          generate_release_notes: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - details
      - setup_and_build
      - testpypi_publish
      - pypi_publish

    if: >
      needs.testpypi_publish.result == 'success' &&
      needs.pypi_publish.result == 'success' &&
      needs.details.outputs.is_prerelease == 'false'

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.details.outputs.tag_name }}
          name: "Version ${{ needs.details.outputs.clean_version }}"
          generate_release_notes: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
